(define (problem ejemplo2_ext4)

  (:domain ejercicios)
  (:objects 
    ej0 ej1 ej2 ej3 ej4 ej5 ej6 ej7 ej8 ej9 ej10 ej11 ej12 ej13 ej14 ej15 ej16 ej17 ej18 ej19 ej20 ej21 ej22 ej23 ej24 ninguno - ejercicio
    dif0 dif1 dif2 dif3 dif4 dif5 dif6 dif7 dif8 dif9 dif10  - dificultad
    dia1 dia2 dia3 dia4 dia5 dia6 dia7 dia8 dia9 dia10 dia11 dia12 dia13 dia14 dia15  - dia
  )
  (:init
    (dia_actual dia1)

    (nulo ninguno)

    (dia_siguiente dia1 dia2)
    (dia_siguiente dia2 dia3)
    (dia_siguiente dia3 dia4)
    (dia_siguiente dia4 dia5)
    (dia_siguiente dia5 dia6)
    (dia_siguiente dia6 dia7)
    (dia_siguiente dia7 dia8)
    (dia_siguiente dia8 dia9)
    (dia_siguiente dia9 dia10)
    (dia_siguiente dia10 dia11)
    (dia_siguiente dia11 dia12)
    (dia_siguiente dia12 dia13)
    (dia_siguiente dia13 dia14)
    (dia_siguiente dia14 dia15)

    (dificultad_siguiente dif0 dif1)
    (dificultad_siguiente dif1 dif2)
    (dificultad_siguiente dif2 dif3)
    (dificultad_siguiente dif3 dif4)
    (dificultad_siguiente dif4 dif5)
    (dificultad_siguiente dif5 dif6)
    (dificultad_siguiente dif6 dif7)
    (dificultad_siguiente dif7 dif8)
    (dificultad_siguiente dif8 dif9)
    (dificultad_siguiente dif9 dif10)
    (dificultad_siguiente dif10 dif10)

    (dificultad_actual ej0 dif9)
    (dificultad_actual ej1 dif3)
    (dificultad_actual ej2 dif9)
    (dificultad_actual ej3 dif2)
    (dificultad_actual ej4 dif7)
    (dificultad_actual ej5 dif9)
    (dificultad_actual ej6 dif4)
    (dificultad_actual ej7 dif7)
    (dificultad_actual ej8 dif3)
    (dificultad_actual ej9 dif7)
    (dificultad_actual ej10 dif9)
    (dificultad_actual ej11 dif10)
    (dificultad_actual ej12 dif2)
    (dificultad_actual ej13 dif5)
    (dificultad_actual ej14 dif10)
    (dificultad_actual ej15 dif10)
    (dificultad_actual ej16 dif3)
    (dificultad_actual ej17 dif5)
    (dificultad_actual ej18 dif1)
    (dificultad_actual ej19 dif9)
    (dificultad_actual ej20 dif3)
    (dificultad_actual ej21 dif6)
    (dificultad_actual ej22 dif8)
    (dificultad_actual ej23 dif7)
    (dificultad_actual ej24 dif1)

    (= (duracion ej0) 5)
    (= (duracion ej1) 20)
    (= (duracion ej2) 10)
    (= (duracion ej3) 5)
    (= (duracion ej4) 15)
    (= (duracion ej5) 15)
    (= (duracion ej6) 5)
    (= (duracion ej7) 20)
    (= (duracion ej8) 10)
    (= (duracion ej9) 25)
    (= (duracion ej10) 10)
    (= (duracion ej11) 10)
    (= (duracion ej12) 20)
    (= (duracion ej13) 30)
    (= (duracion ej14) 15)
    (= (duracion ej15) 25)
    (= (duracion ej16) 15)
    (= (duracion ej17) 20)
    (= (duracion ej18) 10)
    (= (duracion ej19) 25)
    (= (duracion ej20) 20)
    (= (duracion ej21) 20)
    (= (duracion ej22) 5)
    (= (duracion ej23) 20)
    (= (duracion ej24) 15)

    (= (tiempo_dia) 0)

    (precursor ninguno ej0)
    (precursor ninguno ej1)
    (precursor ej11 ej2)
    (precursor ninguno ej3)
    (precursor ej6 ej4)
    (precursor ej23 ej5)
    (precursor ninguno ej6)
    (precursor ninguno ej7)
    (precursor ninguno ej8)
    (precursor ninguno ej9)
    (precursor ninguno ej10)
    (precursor ninguno ej11)
    (precursor ninguno ej12)
    (precursor ninguno ej13)
    (precursor ninguno ej14)
    (precursor ninguno ej15)
    (precursor ninguno ej16)
    (precursor ninguno ej17)
    (precursor ninguno ej18)
    (precursor ninguno ej19)
    (precursor ninguno ej20)
    (precursor ej13 ej21)
    (precursor ninguno ej22)
    (precursor ninguno ej23)
    (precursor ninguno ej24)

    (preparador ej17 ej8)
    (preparador ej9 ej17)
    (preparador ej24 ej18)

  )
  (:goal (and (dia_actual dia15) (dificultad_actual ej10 dif10) (dificultad_actual ej20 dif9) (dificultad_actual ej21 dif7) ))
)
