(define (problem juego_pruebas_3)

  (:domain ejercicios)
  (:objects 
    ej0 ej1 ej2 ej3 ej4 ej5 ej6 ej7 ej8 ej9 ej10 ej11 ej12 ej13 ej14 ej15 ej16 ej17 ej18 ej19 ninguno - ejercicio
    dif0 dif1 dif2 dif3 dif4 dif5 dif6 dif7 dif8 dif9 dif10  - dificultad
    dia1 dia2 dia3 dia4 dia5 dia6 dia7 dia8 dia9 dia10 dia11 dia12 dia13 dia14 dia15  - dia
  )
  (:init
    (dia_actual dia1)

    (nulo ninguno)

    (dia_siguiente dia1 dia2)
    (dia_siguiente dia2 dia3)
    (dia_siguiente dia3 dia4)
    (dia_siguiente dia4 dia5)
    (dia_siguiente dia5 dia6)
    (dia_siguiente dia6 dia7)
    (dia_siguiente dia7 dia8)
    (dia_siguiente dia8 dia9)
    (dia_siguiente dia9 dia10)
    (dia_siguiente dia10 dia11)
    (dia_siguiente dia11 dia12)
    (dia_siguiente dia12 dia13)
    (dia_siguiente dia13 dia14)
    (dia_siguiente dia14 dia15)

    (dificultad_siguiente dif0 dif1)
    (dificultad_siguiente dif1 dif2)
    (dificultad_siguiente dif2 dif3)
    (dificultad_siguiente dif3 dif4)
    (dificultad_siguiente dif4 dif5)
    (dificultad_siguiente dif5 dif6)
    (dificultad_siguiente dif6 dif7)
    (dificultad_siguiente dif7 dif8)
    (dificultad_siguiente dif8 dif9)
    (dificultad_siguiente dif9 dif10)
    (dificultad_siguiente dif10 dif10)

    (dificultad_actual ej0 dif1)
    (dificultad_actual ej1 dif6)
    (dificultad_actual ej2 dif5)
    (dificultad_actual ej3 dif3)
    (dificultad_actual ej4 dif5)
    (dificultad_actual ej5 dif4)
    (dificultad_actual ej6 dif2)
    (dificultad_actual ej7 dif3)
    (dificultad_actual ej8 dif1)
    (dificultad_actual ej9 dif6)
    (dificultad_actual ej10 dif2)
    (dificultad_actual ej11 dif4)
    (dificultad_actual ej12 dif4)
    (dificultad_actual ej13 dif9)
    (dificultad_actual ej14 dif7)
    (dificultad_actual ej15 dif7)
    (dificultad_actual ej16 dif1)
    (dificultad_actual ej17 dif8)
    (dificultad_actual ej18 dif2)
    (dificultad_actual ej19 dif5)

    (= (numero_ej) 0)

    (precursor ninguno ej0)
    (precursor ninguno ej1)
    (precursor ninguno ej2)
    (precursor ninguno ej3)
    (precursor ninguno ej4)
    (precursor ej0 ej5)
    (precursor ninguno ej6)
    (precursor ninguno ej7)
    (precursor ninguno ej8)
    (precursor ninguno ej9)
    (precursor ninguno ej10)
    (precursor ej14 ej11)
    (precursor ej17 ej12)
    (precursor ninguno ej13)
    (precursor ninguno ej14)
    (precursor ninguno ej15)
    (precursor ej11 ej16)
    (precursor ninguno ej17)
    (precursor ninguno ej18)
    (precursor ninguno ej19)

    (preparador ej18 ej4)
    (preparador ej16 ej12)
    (preparador ej13 ej12)

  )
  (:goal (and (dia_actual dia15) (dificultad_actual ej15 dif9) (dificultad_actual ej0 dif7) (dificultad_actual ej10 dif10) ))
)
